TebLocalPlannerROS:
 # Use filtered (Kalman) odometry based from VESC and IMU data.
 odom_topic: odometry/filtered
 #odom_topic: odom
 map_frame: map

 # Trajectory
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.02
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 2

 # Robot
 max_vel_x: 0.25
 max_vel_x_backwards: 0.25
 max_vel_y: 0.0
 max_vel_theta: 0.5 # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
 acc_lim_x: 4.0
 acc_lim_theta: 2.0

 # ********************** Carlike robot parameters ********************
 min_turning_radius: 1.8        # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
 wheelbase: 0.25                # Wheelbase of our robot
 # ********************************************************************

 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "polygon"
   vertices: [[-0.1, -0.125], [-0.1, 0.125], [0.40, 0.125], [0.40, -0.125]]

 # GoalTolerance
 xy_goal_tolerance: 0.5
 yaw_goal_tolerance: 1.6
 free_goal_vel: True

 # Obstacles
 min_obstacle_dist: 0.2 # This value must also include our robot's expansion, since footprint_model is set to "line".
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 0.5
 obstacle_poses_affected: 10
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 10
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 100
 weight_kinematics_forward_drive: 10
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 10
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet

 # Homotopy Class Planner
 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
